Added Ising2DApp example to OSP for debugging.
Ising2DApp throws a an error when editing the Dynamics parameter in the control.

TypeError: can't access property "getPreferredSize$", this.peer is null
@swingjs/j2s/java/awt/Component.js:645:57